# Generated by Django 4.2.5 on 2023-09-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_color_item_gender_item_size_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
